name: flutter_animated_bottom_nav
description: A highly customizable animated bottom navigation with morphing icons, badge support, and smooth transitions
version: 0.0.3
homepage: https://github.com/dhia-bechattaoui/flutter_animated_bottom_nav

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # No assets needed for this package 